#!/bin/bash

# uDosGo Ecosystem Framework Setup
# Comprehensive setup for new installations with proper permissions and repository structure

set -e  # Exit on error

echo "=== uDosGo Ecosystem Framework Setup ==="
echo "Setting up framework for new installations"
echo ""

# Configuration
REPO_ROOTS=(
    "~/uDosGo"
    "~/Code" 
    "~/Vault"
)

VAULT_REPO="git@github.com:fredporter/Vault.git"

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to set proper permissions
set_proper_permissions() {
    local dir_path="$1"
    local owner="$2"
    local group="$3"
    
    echo "Setting permissions for $dir_path..."
    
    # Set directory permissions
    chmod 755 "$dir_path"
    
    # Set ownership if specified
    if [ -n "$owner" ]; then
        sudo chown -R "$owner:$group" "$dir_path" 2>/dev/null || chown -R "$owner:$group" "$dir_path"
    fi
    
    # Set special permissions for sensitive directories
    if [[ "$dir_path" == *"private"* ]] || [[ "$dir_path" == *"secrets"* ]]; then
        chmod 700 "$dir_path"
        echo "✅ Secure permissions set for $dir_path (700)"
    else
        echo "✅ Standard permissions set for $dir_path (755)"
    fi
}

# Function to initialize git repository
default_git_init() {
    local repo_path="$1"
    local repo_name="$2"
    
    if [ -d "$repo_path/.git" ]; then
        echo "✅ Git repository already exists in $repo_path"
        return
    fi
    
    echo "Initializing Git repository for $repo_name..."
    cd "$repo_path"
    
    git init
    git config user.name "uDosGo Ecosystem"
    git config user.email "ecosystem@udosgo.com"
    
    # Create standard .gitignore
    cat > .gitignore << 'EOL'
# uDosGo .gitignore
.DS_Store
*.log
*.swp
*.swo
*.bak
*.tmp
*.backup

# Dependency directories
node_modules/
vendor/

# Environment files
.env
*.env.local
*.env.development
*.env.test
*.env.production

# IDE specific
.idea/
.vscode/
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# Build output
build/
dist/
output/

# Runtime data
pids/
logs/
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov/

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# Grunt intermediate storage (https://github.com/gruntjs/grunt-contrib-qunit#check-in-qunit-fixtures)
.grunt/

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release/

# Dependency directories
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env.test

# parcel-bundler cache (https://parceljs.org/
.cache
.parcel-cache

# Next.js build output
.next/
out/

# Nuxt.js build / generate output
.nuxt/
dist/

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# vscode extensions
.vscode/extensions

# Local History for Visual Studio Code
.history/

# Built Visual Studio Code Extensions
.out/
.vs/
.idea/

# Local build artifacts
bin/
obj/

# CocoaPods
Pods/

# XCode
build/
DerivedData/

# Swift Package Manager
.Package

# Android Studio
.cxx/
*.iml
.idea/
.gradle/
build/

# Unity
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/

# Unreal Engine
Binaries/
DerivedDataCache/
Intermediate/
Saved/

# Godot
.import/
.mono/

# Blender
.blend1
.blend2
.blend3

# Visual Studio
.vs/
*.user
*.userosscache
*.sln.docstates

# JetBrains
.idea/
*.iml

# Python
__pycache__/
*.py[cod]
*$py.class

# Ruby
*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/
/testdb

# Java
*.class
*.jar
*.war
*.ear

# Clojure
*.nrepl-port

# Database
*.sqlite
*.sqlite3
*.sqlite3-journal
*.db
*.db-journal
*.db-wal
*.db-shm

# OS generated files
.ehthumbs.db
.Thumbs.db

# Mac
.DS_Store
.AppleDouble
.LSOverride

# Linux
*~

# Windows
Thumbs.db
Desktop.ini
$RECYCLE.BIN/

# Kubernetes
.kube/

# Docker
.docker/

# Minikube
.minikube/

# Helm
.helm/

# Terraform
.terraform/
terraform.tfstate
terraform.tfstate.backup
*.tfvars
.terraform.lock.hcl

# Ansible
.ansible/

# Chef
.chef/

# Puppet
.puppet/

# Vagrant
.vagrant/

# Packer
.packer/

# Consul
.consul/

# Nomad
.nomad/

# Vault
.vault/

# Private directories
private/
secrets/
.compost/
EOL
    
    git add .gitignore
    git commit -m "Initial commit: Set up .gitignore"
    
    echo "✅ Git repository initialized for $repo_name"
}

# Function to set up repository structure
setup_repository_structure() {
    local repo_path="$1"
    local repo_name="$2"
    
    echo "Setting up structure for $repo_name..."
    
    case "$repo_name" in
        "uDosGo")
            # uDosGo repository structure
            mkdir -p "$repo_path/{Home,3dWorld,Connect,Memory,Users,scripts,dev,Docs,SonicScrewdriver,Vendor,architecture,framework,tools}"
            
            # Create essential files
            cat > "$repo_path/README.md" << 'EOL'
# uDosGo Ecosystem

This is the main uDosGo ecosystem repository containing:

## Core Components
- **Home**: Core home configuration and management
- **3dWorld**: 3D world and spatial computing systems
- **Connect**: Connection management and networking
- **Memory**: Memory systems and data management
- **Users**: User management and authentication

## Development
- **scripts**: Ecosystem management scripts
- **dev**: Development tools and utilities
- **architecture**: System architecture and design
- **framework**: Ecosystem framework components

## Documentation & Tools
- **Docs**: Comprehensive documentation
- **SonicScrewdriver**: Advanced management tools
- **Vendor**: Third-party integrations
- **tools**: Additional tools and utilities

## Getting Started

1. **Set up environment variables**
   ```bash
   export UDOSGO_ROOT="$HOME/uDosGo"
   export PATH="$PATH:$UDOSGO_ROOT/scripts"
   ```

2. **Run ecosystem setup**
   ```bash
   bash $UDOSGO_ROOT/framework/ecosystem_framework_setup.sh
   ```

3. **Explore the ecosystem**
   ```bash
   cd $UDOSGO_ROOT
   ls -la
   ```

## Framework Components

The uDosGo framework provides:
- **Modular architecture** for easy extension
- **Comprehensive scripting** for automation
- **Documentation system** for knowledge management
- **Tool integration** for development workflows

## Repository Management

- **Branching**: Use feature branches for development
- **Commits**: Follow conventional commit messages
- **Pull Requests**: Required for main branch changes
- **Code Reviews**: Mandatory for all contributions

## Support

For issues and questions:
- Check documentation in `Docs/`
- Review architecture in `architecture/`
- Use tools in `SonicScrewdriver/`
- Contact ecosystem team for advanced support
EOL
            ;;
            
        "Code")
            # Code repository structure
            mkdir -p "$repo_path/{Apps,Dev,Vendor,Private,Tools,Libraries,framework,docs,tests,scripts}"
            
            # Create essential files
            cat > "$repo_path/README.md" << 'EOL'
# uDosGo Code Repository

This repository contains all code-related work for the uDosGo ecosystem.

## Structure

- **Apps**: Application development
  - `Marksmith`: Marksmith application
  - `McSnackbar`: McSnackbar application
  - `Utilities`: Utility applications
  - `WebApps`: Web applications
  - `MobileApps`: Mobile applications

- **Dev**: Development projects and experiments
- **Vendor**: Third-party code and dependencies
- **Private**: Private repositories and sensitive code
- **Tools**: Development tools and utilities
- **Libraries**: Shared libraries and components

## Framework
- **framework**: Code framework and architecture
- **docs**: Code-specific documentation
- **tests**: Testing framework and test cases
- **scripts**: Code management scripts

## Getting Started

1. **Set up environment variables**
   ```bash
   export CODE_ROOT="$HOME/Code"
   export PATH="$PATH:$CODE_ROOT/Tools"
   ```

2. **Initialize development environment**
   ```bash
   cd $CODE_ROOT
   bash framework/setup_dev_environment.sh
   ```

3. **Start development**
   ```bash
   cd $CODE_ROOT/Apps/Marksmith
   # Start coding!
   ```

## Development Standards

### Code Style
- Follow language-specific style guides
- Use consistent indentation (4 spaces)
- Include comprehensive documentation
- Write meaningful commit messages

### Testing
- Write tests for all new features
- Maintain >90% code coverage
- Run tests before committing
- Use `bash tests/run_all_tests.sh`

### Documentation
- Document all public APIs
- Update README files regularly
- Use JSDoc/TypeScript annotations
- Keep architecture diagrams current

## Repository Management

- **Branching**: Feature branches with `feature/` prefix
- **Tags**: Version tags with `v*` prefix
- **Releases**: Semantic versioning (MAJOR.MINOR.PATCH)
- **Dependencies**: Document in `package.json`/`requirements.txt`

## Build System

```bash
# Build all applications
bash scripts/build_all.sh

# Build specific application
bash scripts/build_app.sh Marksmith

# Run development server
bash scripts/dev_server.sh
```

## Support

- **Documentation**: `docs/` directory
- **Framework**: `framework/` components
- **Tools**: `Tools/` utilities
- **Contact**: Ecosystem development team
EOL
            ;;
            
        "Vault")
            # Vault repository structure  
            mkdir -p "$repo_path/{docs,user-docs,private,ecosystem,dev,coordination,backups,archive,secrets}"
            mkdir -p "$repo_path/docs/{ecosystem,architecture,guides,reference}"
            mkdir -p "$repo_path/user-docs/{personal,work,projects}"
            mkdir -p "$repo_path/private/{secrets,config,credentials}"
            mkdir -p "$repo_path/ecosystem/{management,integration,scripts}"
            mkdir -p "$repo_path/dev/{docs,specs,designs}"
            mkdir -p "$repo_path/coordination/{meetings,planning,communication}"
            
            # Create essential files
            cat > "$repo_path/README.md" << 'EOL'
# uDosGo Vault

Secure document storage and knowledge management system for the uDosGo ecosystem.

## Structure

### Documentation
- **docs/**: Comprehensive documentation
  - `ecosystem/`: Ecosystem-wide documentation
  - `architecture/`: System architecture documents
  - `guides/`: User and developer guides
  - `reference/`: Technical reference materials

- **user-docs/**: User-specific documentation
  - `personal/`: Personal documents and notes
  - `work/`: Work-related documentation
  - `projects/`: Project-specific documentation

### Ecosystem Management
- **ecosystem/**: Ecosystem management
  - `management/`: Management processes and procedures
  - `integration/`: Integration guides and APIs
  - `scripts/`: Management and synchronization scripts

- **dev/**: Development documentation
  - `docs/`: Development guides and standards
  - `specs/`: Technical specifications
  - `designs/`: System designs and diagrams

- **coordination/**: Team coordination
  - `meetings/`: Meeting notes and agendas
  - `planning/`: Project planning documents
  - `communication/`: Communication records

### Secure Storage
- **private/**: Sensitive information (ENCRYPTED)
  - `secrets/`: Secret keys and credentials
  - `config/`: Configuration files
  - `credentials/`: Access credentials

- **backups/**: System backups
- **archive/**: Long-term archives
- **secrets/**: Additional secure storage

## Usage

### Synchronization

```bash
# Full synchronization
bash ecosystem/scripts/vault_sync_all.sh

# User docs only
bash ecosystem/scripts/sync_user_docs.sh

# Ecosystem docs only
bash ecosystem/scripts/sync_eco_docs.sh
```

### Management

```bash
# Check vault status
bash ecosystem/scripts/vault_status.sh

# Create backup
bash ecosystem/scripts/vault_backup.sh

# Restore from backup
bash ecosystem/scripts/vault_restore.sh backup_path
```

### Documentation Standards

- **Format**: Markdown (.md) for all documents
- **Structure**: Use clear headings and sections
- **Metadata**: Include front matter for important docs
- **Versioning**: Document versions and change history
- **Links**: Use relative links for internal references

## Security

### Access Control
- **Private directories**: 700 permissions only
- **Sensitive files**: Encrypted storage required
- **Access logs**: Maintain access records
- **Audit trail**: Regular security audits

### Encryption
```bash
# Encrypt sensitive files
openssl enc -aes-256-cbc -salt -in file.txt -out file.enc

# Decrypt files
openssl enc -d -aes-256-cbc -in file.enc -out file.txt
```

### Backup Strategy
- **Frequency**: Daily automated backups
- **Retention**: 30-day rotation
- **Storage**: Multiple locations (local + cloud)
- **Testing**: Regular restore testing

## Synchronization Sources

### Primary Sources
1. **Private User Docs**: `git@github.com:fredporter/Vault.git`
2. **Ecosystem Docs**: `~/uDosGo/Docs/`
3. **Coordination Docs**: `~/uDosGo/uDosConnect/docs/`
4. **Development Docs**: `~/uDosGo/dev/docs/`

### Synchronization Schedule
- **Automatic**: Daily at 6:00 AM
- **Manual**: As needed via scripts
- **Conflict Resolution**: Manual review required

## Repository Management

### Git Workflow
```bash
# Add new documents
git add docs/new_document.md
git commit -m "Add new documentation"

# Update existing documents
git add docs/updated_document.md
git commit -m "Update documentation"

# Push changes
git push origin main
```

### Branching Strategy
- **main**: Production-ready documents
- **dev**: Development and draft documents
- **feature/*`: Feature-specific documentation
- **fix/*`: Documentation fixes and updates

## Support

### Troubleshooting

**Permission Issues:**
```bash
chmod -R 700 ~/Vault/private
chmod -R 755 ~/Vault/docs
```

**Synchronization Issues:**
```bash
# Check sync logs
cat ~/Vault/ecosystem/logs/sync.log

# Manual sync
bash ~/Vault/ecosystem/scripts/vault_sync_all.sh
```

**Access Issues:**
```bash
# Set up SSH keys
ssh-keygen -t ed25519 -C "vault@udosgo.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
```

### Contact

- **Documentation Team**: For content questions
- **Security Team**: For access and encryption issues
- **Ecosystem Team**: For integration and synchronization

## Best Practices

1. **Regular Backups**: Always maintain current backups
2. **Document Everything**: If it's not documented, it doesn't exist
3. **Secure Sensitive Data**: Encrypt all sensitive information
4. **Version Control**: Use Git for all document changes
5. **Regular Audits**: Review access and permissions monthly
6. **Consistent Formatting**: Follow documentation standards
7. **Link Integrity**: Verify all links and references
8. **Access Control**: Limit access to sensitive information
EOL
            ;;
    esac
    
    echo "✅ Structure set up for $repo_name"
}

# Function to set up framework components
setup_framework_components() {
    local framework_path="$1"
    
    echo "Setting up framework components..."
    
    # Create framework directory structure
    mkdir -p "$framework_path/{core,scripts,config,docs,tools,integration,security}"
    
    # Create core framework files
    cat > "$framework_path/core/framework_core.sh" << 'EOL'
#!/bin/bash
# uDosGo Framework Core
# Core framework functions for ecosystem management

# Framework version
FRAMEWORK_VERSION="1.0.0"

# Core framework functions
framework_init() {
    echo "Initializing uDosGo Framework v$FRAMEWORK_VERSION"
    
    # Load configuration
    if [ -f "$FRAMEWORK_CONFIG" ]; then
        source "$FRAMEWORK_CONFIG"
    fi
    
    # Set up environment
    setup_environment
    
    # Initialize logging
    init_logging
    
    echo "✅ Framework initialized"
}

setup_environment() {
    # Set default environment variables
    export UDOSGO_FRAMEWORK_ROOT="${UDOSGO_FRAMEWORK_ROOT:-$HOME/uDosGo/framework}"
    export UDOSGO_CONFIG_DIR="${UDOSGO_CONFIG_DIR:-$UDOSGO_FRAMEWORK_ROOT/config}"
    export UDOSGO_LOGS_DIR="${UDOSGO_LOGS_DIR:-$UDOSGO_FRAMEWORK_ROOT/logs}"
    
    # Create directories if they don't exist
    mkdir -p "$UDOSGO_CONFIG_DIR"
    mkdir -p "$UDOSGO_LOGS_DIR"
    
    # Add to PATH
    export PATH="$PATH:$UDOSGO_FRAMEWORK_ROOT/scripts"
    export PATH="$PATH:$UDOSGO_FRAMEWORK_ROOT/tools"
}

init_logging() {
    # Set up logging
    export LOG_FILE="$UDOSGO_LOGS_DIR/framework_$(date +%Y%m%d).log"
    mkdir -p "$(dirname "$LOG_FILE")"
    touch "$LOG_FILE"
    
    log_message "Framework initialization started"
}

log_message() {
    local message="$1"
    local timestamp="$(date +'%Y-%m-%d %H:%M:%S')"
    echo "[$timestamp] $message" | tee -a "$LOG_FILE"
}

# Configuration management
load_config() {
    local config_file="$1"
    if [ -f "$config_file" ]; then
        log_message "Loading configuration from $config_file"
        source "$config_file"
    else
        log_error "Configuration file not found: $config_file"
    fi
}

save_config() {
    local config_file="$1"
    local config_content="$2"
    
    log_message "Saving configuration to $config_file"
    echo "$config_content" > "$config_file"
    chmod 600 "$config_file"
}

# Error handling
log_error() {
    local message="$1"
    local timestamp="$(date +'%Y-%m-%d %H:%M:%S')"
    echo "[$timestamp] ERROR: $message" | tee -a "$LOG_FILE" >&2
}

handle_error() {
    local exit_code="$1"
    local message="$2"
    
    if [ "$exit_code" -ne 0 ]; then
        log_error "$message (exit code: $exit_code)"
        exit "$exit_code"
    fi
}

# Repository management
clone_repository() {
    local repo_url="$1"
    local target_dir="$2"
    local branch="${3:-main}"
    
    log_message "Cloning repository: $repo_url"
    
    if [ -d "$target_dir/.git" ]; then
        log_message "Repository already exists, pulling latest changes"
        cd "$target_dir"
        git pull origin "$branch"
    else
        git clone -b "$branch" "$repo_url" "$target_dir"
    fi
    
    handle_error "$?" "Failed to clone repository: $repo_url"
}

# File management
backup_file() {
    local source="$1"
    local backup_dir="${2:-$UDOSGO_LOGS_DIR/backups}"
    
    mkdir -p "$backup_dir"
    local backup_file="$backup_dir/$(basename "$source").backup_$(date +%Y%m%d_%H%M%S)"
    
    log_message "Backing up $source to $backup_file"
    cp -p "$source" "$backup_file"
    
    handle_error "$?" "Failed to backup file: $source"
}

# Initialize framework
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    framework_init
fi
EOL
    
    # Create framework configuration
    cat > "$framework_path/config/framework_config.sh" << 'EOL'
#!/bin/bash
# uDosGo Framework Configuration

# Framework settings
export FRAMEWORK_VERSION="1.0.0"
export FRAMEWORK_NAME="uDosGo Ecosystem Framework"

# Repository roots
export REPO_ROOTS=(
    "$HOME/uDosGo"
    "$HOME/Code"
    "$HOME/Vault"
)

# Vault configuration
export VAULT_REPO="git@github.com:fredporter/Vault.git"
export VAULT_SYNC_SCHEDULE="0 6 * * *"  # Daily at 6 AM

# Permission settings
export STANDARD_DIR_PERMS="755"
export SECURE_DIR_PERMS="700"
export STANDARD_FILE_PERMS="644"
export SECURE_FILE_PERMS="600"

# Git configuration
export GIT_USER_NAME="uDosGo Ecosystem"
export GIT_USER_EMAIL="ecosystem@udosgo.com"
export GIT_MAIN_BRANCH="main"

# Logging configuration
export LOG_LEVEL="INFO"
export MAX_LOG_FILES="30"
export LOG_FILE_SIZE="10MB"

# Security settings
export ENCRYPTION_ALGORITHM="AES-256-CBC"
export BACKUP_RETENTION_DAYS="30"

# Synchronization settings
export SYNC_TIMEOUT="300"
export SYNC_RETRIES="3"
export SYNC_RETRY_DELAY="10"

# Development settings
export DEV_ENVIRONMENT="development"
export PROD_ENVIRONMENT="production"
export TEST_ENVIRONMENT="test"

# Initialize framework configuration
framework_init() {
    echo "Loading uDosGo Framework Configuration v$FRAMEWORK_VERSION"
    
    # Set git configuration
    git config --global user.name "$GIT_USER_NAME"
    git config --global user.email "$GIT_USER_EMAIL"
    
    echo "✅ Framework configuration loaded"
}

# Call initialization if run directly
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    framework_init
fi
EOL
    
    # Create framework scripts
    cat > "$framework_path/scripts/framework_setup.sh" << 'EOL'
#!/bin/bash
# uDosGo Framework Setup Script

# Load framework core
source "$(dirname "$0")/../core/framework_core.sh"

framework_setup() {
    log_message "Starting uDosGo Framework setup"
    
    # Load configuration
    load_config "$(dirname "$0")/../config/framework_config.sh"
    
    # Set up repository roots
    setup_repository_roots
    
    # Set up framework components
    setup_framework_components
    
    # Set up synchronization
    setup_synchronization
    
    # Set up security
    setup_security
    
    # Complete setup
    complete_setup
    
    log_message "uDosGo Framework setup completed successfully"
}

setup_repository_roots() {
    log_message "Setting up repository roots"
    
    for repo_root in "${REPO_ROOTS[@]}"; do
        if [ ! -d "$repo_root" ]; then
            log_message "Creating repository root: $repo_root"
            mkdir -p "$repo_root"
            set_proper_permissions "$repo_root"
        else
            log_message "Repository root already exists: $repo_root"
        fi
    done
    
    log_message "✅ Repository roots set up"
}

setup_framework_components() {
    log_message "Setting up framework components"
    
    # Create framework directories
    local framework_root="$UDOSGO_FRAMEWORK_ROOT"
    mkdir -p "$framework_root/{core,scripts,config,docs,tools,integration,security,logs}"
    
    # Set permissions
    set_proper_permissions "$framework_root"
    
    log_message "✅ Framework components set up"
}

setup_synchronization() {
    log_message "Setting up synchronization"
    
    # Create synchronization directories
    mkdir -p "$HOME/Vault/ecosystem/scripts"
    
    # Set up cron jobs
    setup_cron_jobs
    
    log_message "✅ Synchronization set up"
}

setup_cron_jobs() {
    log_message "Setting up cron jobs"
    
    # Remove existing cron jobs
    crontab -l 2>/dev/null | grep -v "vault_sync" | crontab - 2>/dev/null || true
    
    # Add new cron job
    (crontab -l 2>/dev/null; echo "$VAULT_SYNC_SCHEDULE bash $HOME/Vault/ecosystem/scripts/vault_sync_all.sh") | crontab -
    
    log_message "✅ Cron jobs set up"
}

setup_security() {
    log_message "Setting up security"
    
    # Create security directories
    mkdir -p "$HOME/Vault/private/secrets"
    mkdir -p "$HOME/Vault/private/config"
    mkdir -p "$HOME/Vault/private/credentials"
    
    # Set secure permissions
    chmod 700 "$HOME/Vault/private"
    chmod 700 "$HOME/Vault/private/secrets"
    chmod 700 "$HOME/Vault/private/config"
    chmod 700 "$HOME/Vault/private/credentials"
    
    log_message "✅ Security set up"
}

complete_setup() {
    log_message "Completing setup"
    
    # Create setup completion marker
    echo "Framework setup completed on $(date)" > "$UDOSGO_FRAMEWORK_ROOT/.setup_complete"
    
    # Display setup summary
    display_setup_summary
    
    log_message "✅ Setup completed"
}

display_setup_summary() {
    echo ""
    echo "=== uDosGo Framework Setup Complete ==="
    echo ""
    echo "Repository Roots:"
    for repo_root in "${REPO_ROOTS[@]}"; do
        echo "  - $repo_root"
    done
    echo ""
    echo "Framework Components:"
    echo "  - Core: $UDOSGO_FRAMEWORK_ROOT/core"
    echo "  - Scripts: $UDOSGO_FRAMEWORK_ROOT/scripts"
    echo "  - Config: $UDOSGO_FRAMEWORK_ROOT/config"
    echo "  - Tools: $UDOSGO_FRAMEWORK_ROOT/tools"
    echo ""
    echo "Synchronization:"
    echo "  - Schedule: $VAULT_SYNC_SCHEDULE"
    echo "  - Scripts: $HOME/Vault/ecosystem/scripts"
    echo ""
    echo "Next Steps:"
    echo "  1. source ~/.profile"
    echo "  2. Test framework: bash $UDOSGO_FRAMEWORK_ROOT/scripts/framework_setup.sh"
    echo "  3. Review configuration: $UDOSGO_FRAMEWORK_ROOT/config/framework_config.sh"
    echo ""
}

# Run setup if called directly
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    framework_setup
fi
EOL
    
    # Make framework scripts executable
    chmod +x "$framework_path/core/framework_core.sh"
    chmod +x "$framework_path/config/framework_config.sh"
    chmod +x "$framework_path/scripts/framework_setup.sh"
    
    echo "✅ Framework components set up"
}

# Function to commit and push changes
commit_and_push_changes() {
    local repo_path="$1"
    local repo_name="$2"
    local commit_message="$3"
    
    echo "Committing and pushing changes for $repo_name..."
    
    cd "$repo_path"
    
    # Check if there are changes
    if [ -z "$(git status --porcelain)" ]; then
        echo "✅ No changes to commit in $repo_name"
        return
    fi
    
    # Add all changes
    git add .
    
    # Commit changes
    git commit -m "$commit_message"
    
    # Push to remote if available
    if git remote | grep -q "origin"; then
        git push origin "$(git rev-parse --abbrev-ref HEAD)"
        echo "✅ Changes pushed to remote for $repo_name"
    else
        echo "✅ Changes committed locally for $repo_name (no remote configured)"
    fi
}

# Main setup function
main_setup() {
    echo "Starting uDosGo Ecosystem Framework setup..."
    
    # Step 1: Check prerequisites
    echo "Step 1: Checking prerequisites..."
    
    if ! command_exists git; then
        echo "Error: Git is required but not installed"
        exit 1
    fi
    
    if ! command_exists curl; then
        echo "Error: curl is required but not installed"
        exit 1
    fi
    
    echo "✅ Prerequisites satisfied"
    
    # Step 2: Set up repository roots
    echo ""
    echo "Step 2: Setting up repository roots..."
    
    for repo_root in "${REPO_ROOTS[@]}"; do
        if [ ! -d "$repo_root" ]; then
            echo "Creating repository root: $repo_root"
            mkdir -p "$repo_root"
        else
            echo "✅ Repository root exists: $repo_root"
        fi
        
        set_proper_permissions "$repo_root" "$USER" "$USER"
    done
    
    echo "✅ Repository roots set up"
    
    # Step 3: Set up repository structures
    echo ""
    echo "Step 3: Setting up repository structures..."
    
    for repo_root in "${REPO_ROOTS[@]}"; do
        local repo_name=$(basename "$repo_root")
        setup_repository_structure "$repo_root" "$repo_name"
    done
    
    echo "✅ Repository structures set up"
    
    # Step 4: Initialize git repositories
    echo ""
    echo "Step 4: Initializing git repositories..."
    
    for repo_root in "${REPO_ROOTS[@]}"; do
        local repo_name=$(basename "$repo_root")
        default_git_init "$repo_root" "$repo_name"
    done
    
    echo "✅ Git repositories initialized"
    
    # Step 5: Set up framework components
    echo ""
    echo "Step 5: Setting up framework components..."
    
    local framework_path="~/uDosGo/framework"
    setup_framework_components "$framework_path"
    
    echo "✅ Framework components set up"
    
    # Step 6: Set up Vault synchronization
    echo ""
    echo "Step 6: Setting up Vault synchronization..."
    
    if [ -f "~/vault_sync_setup.sh" ]; then
        bash ~/vault_sync_setup.sh
        echo "✅ Vault synchronization set up"
    else
        echo "⚠️  Vault sync script not found, skipping"
    fi
    
    # Step 7: Commit and push changes
    echo ""
    echo "Step 7: Committing and pushing changes..."
    
    local timestamp="$(date +%Y-%m-%d\ %H:%M:%S)"
    local commit_message="Framework setup: $timestamp"
    
    for repo_root in "${REPO_ROOTS[@]}"; do
        local repo_name=$(basename "$repo_root")
        commit_and_push_changes "$repo_root" "$repo_name" "$commit_message"
    done
    
    echo "✅ Changes committed and pushed"
    
    # Step 8: Final verification
    echo ""
    echo "Step 8: Final verification..."
    
    echo "Repository Status:"
    for repo_root in "${REPO_ROOTS[@]}"; do
        local repo_name=$(basename "$repo_root")
        echo "  $repo_name: $(cd "$repo_root" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "Not a git repo")"
    done
    
    echo ""
    echo "=== uDosGo Ecosystem Framework Setup Complete ==="
    echo ""
    echo "Setup Summary:"
    echo "  - Repository roots: ${#REPO_ROOTS[@]}"
    echo "  - Framework components: Installed"
    echo "  - Vault synchronization: Configured"
    echo "  - Git repositories: Initialized"
    echo "  - Permissions: Configured"
    echo ""
    echo "Next Steps:"
    echo "  1. source ~/.profile"
    echo "  2. Test framework: bash ~/uDosGo/framework/scripts/framework_setup.sh"
    echo "  3. Set up SSH keys for GitHub access"
    echo "  4. Configure private repository access"
    echo "  5. Run initial synchronization"
    echo ""
    echo "Documentation:"
    echo "  - Framework docs: ~/uDosGo/framework/docs"
    echo "  - Ecosystem docs: ~/uDosGo/Docs"
    echo "  - Vault docs: ~/Vault/docs"
    echo ""
}

# Run main setup
main_setup