[build]
rustflags = ["--cfg", "user_mode"]

[target.'cfg(not(debug_assertions))']
rustflags = ["--cfg", "user_mode"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true