#!/bin/bash
# promote.sh - Promote a module from Sandbox to Registry

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 <module-name> <version> [source-dir]"
    echo "Example: $0 ok-helper 1.0.0 ../Sandbox/ok-helper"
    exit 1
fi

MODULE_NAME=$1
VERSION=$2
SOURCE_DIR=${3:-"../Sandbox/$MODULE_NAME"}
REGISTRY_DIR="$(dirname "$0")/../Registry/modules/$MODULE_NAME"

if [ ! -d "$SOURCE_DIR" ]; then
    echo "Error: Source directory $SOURCE_DIR not found"
    exit 1
fi

# Create registry directory structure
mkdir -p "$REGISTRY_DIR/$VERSION"

# Copy module to registry
cp -r "$SOURCE_DIR"/* "$REGISTRY_DIR/$VERSION/"

# Create version file
cat > "$REGISTRY_DIR/$VERSION/VERSION" << EOF
version: $VERSION
promoted: $(date +%Y-%m-%d)
promoted_by: $(whoami)
EOF

# Update registry manifest
MANIFEST_FILE="$(dirname "$0")/../Registry/manifest.yaml"
mkdir -p "$(dirname "$MANIFEST_FILE")"

if [ ! -f "$MANIFEST_FILE" ]; then
    cat > "$MANIFEST_FILE" << EOF
# uDosGo Registry Manifest
# Automatically generated by promote.sh

modules:
EOF
fi

# Add module to registry manifest if not already present
if ! grep -q "name: $MODULE_NAME" "$MANIFEST_FILE"; then
    cat >> "$MANIFEST_FILE" << EOF
  - name: $MODULE_NAME
    version: $VERSION
    path: modules/$MODULE_NAME/$VERSION
    promoted: $(date +%Y-%m-%d)
EOF
fi

# Create symlink for latest version
rm -f "$REGISTRY_DIR/latest"
ln -s "$VERSION" "$REGISTRY_DIR/latest"

# Update Registry README
README_FILE="$(dirname "$0")/../Registry/README.md"
if [ ! -f "$README_FILE" ]; then
    cat > "$README_FILE" << 'EOF'
# uDosGo Registry

Promoted modules, plugins, themes, and extensions for the uDos platform.

## Current Modules

This file is automatically updated by the promotion script.
EOF
fi

echo "✓ Promoted $MODULE_NAME v$VERSION to Registry"
echo "  Location: $REGISTRY_DIR/$VERSION"
echo "  Manifest: $MANIFEST_FILE"
echo "  Latest: $REGISTRY_DIR/latest -> $VERSION"

exit 0