"""
Site Exporter — high-level site generation from uCode1 data.

Provides SiteExporter for building complete static sites from
snacks, binders, relics, and Liquid-rendered content.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from .engine import ExportEngine, ExportFormat, ExportOptions


@dataclass
class SiteConfig:
    """Configuration for site generation."""
    title: str = "uCode1 Site"
    description: str = "Generated by uCode1 Export Engine"
    author: str = "uDos"
    output_dir: str = "./dist"
    theme: str = "bbcbasic"
    include_widgets: bool = True
    include_nav: bool = True
    minify: bool = False
    copy_assets: bool = True
    grid_cols: int = 40
    grid_rows: int = 24


class SiteExporter:
    """
    High-level site exporter that orchestrates the export of
    multiple uCode1 components into a complete static site.
    """

    def __init__(self, config: Optional[SiteConfig] = None):
        self.config = config or SiteConfig()
        self._engine = ExportEngine(ExportOptions(
            output_dir=self.config.output_dir,
            format=ExportFormat.FULL_SITE,
            theme=self.config.theme,
            title=self.config.title,
            include_widgets=self.config.include_widgets,
            include_nav=self.config.include_nav,
            minify=self.config.minify,
            copy_assets=self.config.copy_assets,
            grid_cols=self.config.grid_cols,
            grid_rows=self.config.grid_rows,
        ))

    def export_all(
        self,
        snacks: Optional[List[Dict[str, Any]]] = None,
        binders: Optional[List[Dict[str, Any]]] = None,
        relics: Optional[List[Dict[str, Any]]] = None,
        liquid_pages: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """
        Export all components as a complete static site.

        Args:
            snacks: List of snack dicts
            binders: List of binder dicts
            relics: List of relic dicts
            liquid_pages: List of dicts with 'name', 'html', 'context' keys

        Returns:
            Path to the generated index.html
        """
        pages: List[Dict[str, Any]] = []

        # Add snack pages
        if snacks:
            for snack in snacks:
                slug = snack.get("name", snack.get("id", "untitled")).lower().replace(" ", "-")
                html = self._engine.export_snack(snack)
                pages.append({
                    "slug": slug,
                    "title": f"Snack: {snack.get('name', 'Untitled')}",
                    "body": f'<p>Exported: <a href="{slug}.html">{snack.get("name", "Untitled")}</a></p>',
                })

        # Add binder pages
        if binders:
            for binder in binders:
                meta = binder.get("metadata", {})
                name = meta.get("name", "untitled-binder")
                slug = name.lower().replace(" ", "-")
                self._engine.export_binder(binder)
                pages.append({
                    "slug": slug,
                    "title": f"Binder: {name}",
                    "body": f'<p>Exported: <a href="{slug}.html">{name}</a></p>',
                })

        # Add relic pages
        if relics:
            for relic in relics:
                meta = relic.get("metadata", {})
                name = meta.get("name", "untitled-relic")
                slug = name.lower().replace(" ", "-")
                self._engine.export_relic(relic)
                pages.append({
                    "slug": slug,
                    "title": f"Relic: {name}",
                    "body": f'<p>Exported: <a href="{slug}.html">{name}</a></p>',
                })

        # Add Liquid pages
        if liquid_pages:
            for lp in liquid_pages:
                name = lp.get("name", "untitled")
                slug = name.lower().replace(" ", "-")
                self._engine.export_liquid(
                    name,
                    lp.get("html", ""),
                    lp.get("context"),
                )
                pages.append({
                    "slug": slug,
                    "title": f"Template: {name}",
                    "body": f'<p>Exported: <a href="{slug}.html">{name}</a></p>',
                })

        # Generate the site index
        return self._engine.export_site(pages, self.config.title)
